#配置eureka 的注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 注册服务的端口
server:
  port: 8888

#配置当前服务的名称
spring:
  application:
    name: banksys-config #配置服务名称
  zipkin:
    base-url: http://localhost:9411
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/   # 配置文件所在目录，classpath（类路径）和（系统文件路径） file两种

  boot:
    admin:
      client:
        url: http://localhost:8084
