server:
  port: 8084

spring:
 application:
    name: banksys-admin
 zipkin:
   base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: health, info #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: always  #health endpoint是否必须显示全部细节

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


